import { Project } from '../app/models/project';

// jenkProject
export const CONFIGURATIONS: Project [] = [
  // {
  //   'bitBucketName': 'quick-access-viewer',
  //   'bitBucketProject': 'OB',
  //   'jenkinsProgram': 'CSP',
  //   'jenkinsJobLvl1': 'ngWeb',
  //   'jenkinsJobLvl2': 'quick-access-viewer',
  //   'jenkinsJobLvl3': 'develop',
  // },
  {
    'bitBucketName': 'evolution-api',
    'bitBucketProject': 'OB',
    'jenkinsProgram': 'csp',
    'jenkinsJobLvl1': 'evolution-api',
    'jenkinsJobLvl2': 'evolution-api',
    'jenkinsJobLvl3': 'develop',
  },
  {
    'bitBucketName': 'experience',
    'bitBucketProject': 'CSP',
    'jenkinsProgram': 'csp',
    'jenkinsJobLvl1': 'Content Services Platform',
    'jenkinsJobLvl2': 'experience',
    'jenkinsJobLvl3': 'develop',
  },
  {
    'bitBucketName': 'Evolution IDP',
    'bitBucketProject': 'CSP',
    'jenkinsProgram': 'csp',
    'jenkinsJobLvl1': 'identity team',
    'jenkinsJobLvl2': 'identityprovider',
    'jenkinsJobLvl3': 'master',
  },
  // {
  //   'bitBucketName': 'experience platform',
  //   'bitBucketProject': 'CSP',
  //   'jenkinsProgram': 'CSP',
  //   'jenkinsJobLvl1': 'Content Services Platform',
  //   'jenkinsJobLvl2': 'experience-platform-site',
  //   'jenkinsJobLvl3': 'develop',
  // },
  // {
  //   'bitBucketName': 'experience experimental',
  //   'bitBucketProject': 'CSP',
  //   'jenkinsProgram': 'CSP',
  //   'jenkinsJobLvl1': 'Content Services Platform',
  //   'jenkinsJobLvl2': 'hyland-experimental-components',
  //   'jenkinsJobLvl3': 'master',
  // },
  // {
  //   'bitBucketName': 'mobile rover',
  //   'bitBucketProject': 'CSP',
  //   'jenkinsProgram': 'CSP',
  //   'jenkinsJobLvl1': 'ngweb',
  //   'jenkinsJobLvl2': 'mobile-rover',
  //   'jenkinsJobLvl3': 'master',
  // },
  // {
  //   'bitBucketName': 'hyland graphql',
  //   'bitBucketProject': 'CSP',
  //   'jenkinsProgram': 'CSP',
  //   'jenkinsJobLvl1': 'ngweb',
  //   'jenkinsJobLvl2': 'hyland-graphql',
  //   'jenkinsJobLvl3': 'master',
  // },
  {
    'bitBucketName': 'sharebase',
    'bitBucketProject': 'cloud',
    'jenkinsProgram': 'cloud',
    'jenkinsJobLvl1': 'ShareBase',
    'jenkinsJobLvl2': 'sharebase-web',
    'jenkinsJobLvl3': 'develop',
  },
  {
    'bitBucketName': 'API governance specs',
    'bitBucketProject': 'ag',
    'jenkinsProgram': 'ag',
    'jenkinsJobLvl1': 'AG',
    'jenkinsJobLvl2': 'specifications',
    'jenkinsJobLvl3': 'master',
  },
  {
    'bitBucketName': 'Astra',
    'bitBucketProject': 'healthcarecs',
    'jenkinsProgram': 'healthcarecs',
    'jenkinsJobLvl1': 'Provider Access',
    'jenkinsJobLvl2': 'astra',
    'jenkinsJobLvl3': 'develop',
  },
  {
    'bitBucketName': 'Combined Viewer',
    'bitBucketProject': 'cv-web',
    'jenkinsProgram': 'insurance',
    'jenkinsJobLvl1': 'cv-web',
    'jenkinsJobLvl2': 'combinedviewer.web',
    'jenkinsJobLvl3': 'develop',
  },
];

